# Copyright 2022 Ivan Guerreschi <ivan.guerreschi.dev@gmail.com>.
# All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

version: '3'

tasks:
  run:
    cmds:
      - go run main.go
  build:
    cmds:
      - go build
